import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/header/header'
import Footer from './ui/footer/footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Urban Insights',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className+" h-screen flex flex-col"}>
        <Header/>
        <div className='flex-grow mt-[80px] flex justify-center items-center px-32 bg-transparent'>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
